# <Niravra Kar>, <001252638>, <kar.n@husky.neu.edu>
# <Sumedh Saraf>, <001267030>, <saraf.s@husky.neu.edu>
# <Parakh Mahajan>, <001236045>, <mahajan.pa@husky.neu.edu>
# <Ashwini Thaokar>, <001282202>, <thaokar.a@husky.neu.edu>

language:
  - java

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

sudo: false

install: true

script:
  - ./gradlew build
  - ./gradlew war


after_success:
  - mkdir codedeploy
  - zip -r csye6225-fall2017-codedeploy.zip build/libs/ROOT.war appspec.yml
  - ls -al
  - mv csye6225-fall2017-codedeploy.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:

  - provider: s3
  - access_key_id: AKIAJAOB2INYLKYO4LTA
  - secret_access_key:
     secure: ldjcUYwzKwwJw5USkPxx8UBj9qB6sqDpA2zDB5DzeJTZCDpwkjUVz7tscjeMX2XN1ON0p7aRGcECEQUidfL0Ty2Z2g1SJ0MUtGm+3IaIuZPiQfxCc9g9+qXKGa9EqwWu5PKy9uw/MqR1QLTmoaMfrvz2BwMwON9gUIKgshhlDPq3k7TLR8gIDnAk/UTwWd7QPLD+lHUESOVOydo2wXCSeRcrdtDAv+f7cggoR1DyTzu0Dt2QuIWcHgwkhjCTpBzfmfR9kYnjMkSeBZa+sj30l24MLU4jrM4hAqc9wN6FXuDHUplUTV7tZW+8x6IdgfPA5gTr/nt9qrReGH38NS87TckK7PunvjgjTj73Gv7mm/e75msVoPsypkmwA1rlQQDBkJaFTcK7cCA0sV7cla5ccNMsr1qdsG7/GdohXq/6uDlocyl4R32geEYd1uSPpp9TbXP0pv5/FkoltcDilKjoPZiSF5Z/MTmhyJbm5QHoWkoD/Sf1cKVqajKNwZXBQvVXno8sRQtsiHfJYi7dMJZzKVHbU843qhE+lZ1cGp3jdxqd3Bu+nbJt3PonDqZhD/GRlDuGrnfEw7cfjc8vi8nyEurbILf6L/vPadWDLP5KJEQXyXVST4IaKVYzicsvpAS5+hJlpEdeeosRS0LOwSAGoIbvFKehe9yCz0Q7oWbp25U=
  - local_dir: codedeploy
  - bucket: code-deploy.csye6225-fall2017.karn.com
  - region: us-east-1
  - skip_cleanup: true
  - on:
     all-branches: true

  - provider: codedeploy
  - access_key_id: AKIAJAOB2INYLKYO4LTA
  - secret_access_key:
      secure: ldjcUYwzKwwJw5USkPxx8UBj9qB6sqDpA2zDB5DzeJTZCDpwkjUVz7tscjeMX2XN1ON0p7aRGcECEQUidfL0Ty2Z2g1SJ0MUtGm+3IaIuZPiQfxCc9g9+qXKGa9EqwWu5PKy9uw/MqR1QLTmoaMfrvz2BwMwON9gUIKgshhlDPq3k7TLR8gIDnAk/UTwWd7QPLD+lHUESOVOydo2wXCSeRcrdtDAv+f7cggoR1DyTzu0Dt2QuIWcHgwkhjCTpBzfmfR9kYnjMkSeBZa+sj30l24MLU4jrM4hAqc9wN6FXuDHUplUTV7tZW+8x6IdgfPA5gTr/nt9qrReGH38NS87TckK7PunvjgjTj73Gv7mm/e75msVoPsypkmwA1rlQQDBkJaFTcK7cCA0sV7cla5ccNMsr1qdsG7/GdohXq/6uDlocyl4R32geEYd1uSPpp9TbXP0pv5/FkoltcDilKjoPZiSF5Z/MTmhyJbm5QHoWkoD/Sf1cKVqajKNwZXBQvVXno8sRQtsiHfJYi7dMJZzKVHbU843qhE+lZ1cGp3jdxqd3Bu+nbJt3PonDqZhD/GRlDuGrnfEw7cfjc8vi8nyEurbILf6L/vPadWDLP5KJEQXyXVST4IaKVYzicsvpAS5+hJlpEdeeosRS0LOwSAGoIbvFKehe9yCz0Q7oWbp25U=
  - bucket: code-deploy.csye6225-fall2017.karn.com
  - key: csye6225-fall2017-codedeploy.zip
  - bundle_type: zip
  - application: CSYE6225Project
  - deployment_group: CSYE6225Project
  - region: us-east-1
  - wait-until-deployed: true



notifications:
  email:
    recipients:
      - saraf.s@husky.neu.edu
      - kar.n@husky.neu.edu
      - mahajan.pa@husky.neu.edu
      - thaokar.a@husky.neu.edu
