# <Niravra Kar>, <001252638>, <kar.n@husky.neu.edu>
# <Sumedh Saraf>, <001267030>, <saraf.s@husky.neu.edu>
# <Parakh Mahajan>, <001236045>, <mahajan.pa@husky.neu.edu>
# <Ashwini Thaokar>, <001282202>, <thaokar.a@husky.neu.edu>

language:
  - java

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

sudo: false

install: true

script:
  - ./gradlew build
  - ./gradlew war


after_success:
  - mkdir codedeploy
  - zip -r csye6225-fall2017-codedeploy.zip build/libs/ROOT.war appspec.yml
  - ls -al
  - mv csye6225-fall2017-codedeploy.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:

 - provider: s3
   access_key_id: AKIAI7P53JJ3GMZMG2DA
   secret_access_key:
    secure: nqi/VmvU5KvWy4DBIxbNsg98nCBxWqceDr8pZmG3PLbAD6D/yexgZKfek8FTjM7kgAIy01sjjiMAoC5JbOn2HV/MUOg1kQS4iwHbappIaJxtQxlkHgsRuqyOmG60+l4kX0K5NXRYkj8vjKHaP9KbwSQABcvXGIud7wVxG+DFG6ouHfYmcFT9J4EUH+pgPRdQkkafQpmABMldbmVExV5okUTNNbCYNV9IbOnYqnxLdvj+5mHeKfKpUuh8XVD7g2oduPQvU9UoqJmRyh5AgMcS3rKf55lFF1eaYPb/Elomz3QboWA9b4imKSU8Rdm40Fo6H0LBa0GWjxh7l3aOnLmduNYOoT+0/iLskJIA8MshbRB4s5a5REctyUTpjiTzJE7n3zlmt4sU9NQQhpfgbIiiqH7GiS3HyjtedMQ/dBppbeK+EPez1bU8TFxv13lLe9Aj/P7PAVP/qJegLcViOSdgni94OsCF1XEyTqYYv9em3luXVtTu7lg/q0L65tjMp+kGTcVBeJNQnI4SKPXndGaaXD7YaM9xiQMNCtbqauWx2+qTO+XFwZlxpFnCc1XWcHqreQEuCDKNCkKZA7iG6K3LhAZ2XrFHBM1P+rnEciM3IsjLWAFT0rXy4yk0UVjigniYHIKTBS3zpDapqAksE4JZR1lG4xCEtoR29VkmDOz1CJU=
   local_dir: codedeploy
   bucket: code-deploy.csye6225-fall2017.karn.com
   region: us-east-1
   skip_cleanup: true
   on:
     all-branches: true

 - provider: codedeploy
   access_key_id: AKIAI7P53JJ3GMZMG2DA
   secret_access_key:
    secure: llR3H4Wpc5Drka1K1yzKteqRkZPdyUmpOHafoD4x5VTBth5z5zmtRnaNmBxoTh8PGxulAsu6ngKw6keJHq/0hsD2nJcDa2cAAl96WqGBa1trSBSZahprqbtKtawwmgbuyulVjkDvbg3ZmupUaG7pb3k4k5TFUsrTFyRo7PVDuD0yG3lh0Y9piiJJbRPCSCABncXk5nomKC1mv3HgYZovfLVs7bjTAJvKNqoYVOgmEOA5gZnqOofF4WXbcUeavvU+jK20LkHVy24AfSuxdNrOvuMFeM/ClS8AiQk7vvvzmW8Cz0XvU0G5H9R3eD2VgwllTCGHYfX+6XH3aU0428w9tdWUuTCecE8JQKRtHAZ72VQR6VrJkD+Os+vihPwpUg3NMoVsoYB/Z0akHF71aQ0AOPJDSfw8Gi0joiGpnRgwadREchukjAStX5X4+HHdThUvuoJydKaAQ6HpaAsdVjwFSkehH21DjsaCd00snIEIMsdebIq25pSsV1T+9Wj6imNr7SzDoaR4R/pQdcxjUseOIKYg2FqQJt+njmVmyUCZqiqZ3py/1x74PHV9yignjTbvcc/Z488WCmhikl4b08TRYE40AvOD0QO7BsDIBrNhpXhFKH7PrNODgZWWpXbWN6vdklcm8Hbuy35TKLV1Hr40idmEKirzWJF+TuUIRO4mY3I=    
   bucket: code-deploy.csye6225-fall2017.karn.com
   key: csye6225-fall2017-codedeploy.zip
   bundle_type: zip
   application: CSYE6225Project
   deployment_group: CSYE6225Project
   region: us-east-1
   wait-until-deployed: true



notifications:
  email:
    recipients:
      - saraf.s@husky.neu.edu
      - kar.n@husky.neu.edu
      - mahajan.pa@husky.neu.edu
      - thaokar.a@husky.neu.edu
