# <Niravra Kar>, <001252638>, <kar.n@husky.neu.edu>
# <Sumedh Saraf>, <001267030>, <saraf.s@husky.neu.edu>
# <Parakh Mahajan>, <001236045>, <mahajan.pa@husky.neu.edu>
# <Ashwini Thaokar>, <001282202>, <thaokar.a@husky.neu.edu>

language:
  - java

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

sudo: false

install: true

script:
  - ./gradlew build
  - ./gradlew war


after_success:
  - mkdir codedeploy
  - zip -r csye6225-fall2017-codedeploy.zip build/libs/ROOT.war appspec.yml
  - ls -al
  - mv csye6225-fall2017-codedeploy.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:

  - provider: s3
  - access_key_id: $access_key
  - secret_access_key:
     secure: ${secrete_access_key}
  - local_dir: codedeploy
  - bucket: ${s3_bucket_name}
  - region: us-east-1
  - skip_cleanup: true
  - on:
     all-branches: true

  - provider: codedeploy
  - access_key_id: ${access_key}
  - secret_access_key:
      secure: ${secrete_access_key}
  - bucket: ${s3_bucket_name}
  - key: csye6225-fall2017-codedeploy.zip
  - bundle_type: zip
  - application: ${codedeploy_application_name}
  - deployment_group: ${codedeploy_application_group}
  - region: us-east-1
  - wait-until-deployed: true



notifications:
  email:
    recipients:
      - saraf.s@husky.neu.edu
      - kar.n@husky.neu.edu
      - mahajan.pa@husky.neu.edu
      - thaokar.a@husky.neu.edu
